language: python
python:
# only test against versions: 
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

before_script:
  - python test_user.py 
  - python test_orders.py
  # - cd tests
script: 
  - pytest
  - pytest --cov=.
after_success:
- coveralls